language: c++

branches:
  only:
    - master

dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - mesa-utils
            - xorg-dev
            - libglu1-mesa-dev
            # - libdrm2
            - llvm-5.0-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && OSMESA=ON"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && OSMESA=OFF"

before_install:
    - eval "${MATRIX_EVAL}"

    ############################################################################
    # Update OS X homebrew
    ############################################################################
    - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew update
        softwareupdate --install zlib
        brew install php54 --with-thread-safety
        brew install php54-pthreads
      fi

install:
  ############################################################################
  # All compiled dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew outdated cmake || brew upgrade cmake
    fi
  - cmake --version

  ############################################################################
  # Install OSMesa
  ############################################################################
  - |
    mkdir mesa
    pushd mesa && MESA_OUTPUT_PATH=`pwd` && popd
    wget ftp://ftp.freedesktop.org/pub/mesa/17.0.0/mesa-17.0.0.tar.xz
    tar xvf mesa-17.0.0.tar.xz
    cd mesa-17.0.0
    ./configure \
        --prefix=$MESA_OUTPUT_PATH \
        --enable-osmesa \
        --disable-driglx-direct \
        --disable-dri \
        --with-gallium-drivers=swrast \
        --disable-egl \
        --enable-gbm=no
    make -j12
    make install
    cd ..

script:
  ############################################################################
  # Build project and run CPU based tests
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  # - cmake -DOFFSCREEN_MESA=${OSMESA} ..
  - cmake -DOFFSCREEN_MESA=ON ..
  - make -j
  # - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then ./thirdparty/glfw-build/examples/offscreen; fi;
  - ./thirdparty/glfw-build/examples/offscreen

notifications:
  on_success: never
  on_failure: never
